# 必须设置 site.url 才能生成正确的绝对链接
url: "https://pumadong.github.io" 
baseurl: "" # 如果你的项目在子目录下，请填写子目录名


title: 讨论一下架构
description: 老骥伏枥，志在千里；烈士暮年，壮心不已 ^_^

author:
  email: puma.dong@hotmail.com

# 在 2025 年，GitHub Pages 默认提供的 Jekyll 环境中，minima 主题默认使用的版本依然是 2.5.x 系列。
# 我们使用master分支
remote_theme: jekyll/minima@master

 # light (默认), dark, classic, solarized
minima:
  skin: classic
  hide_site_feed_link：true

