# 必须设置 site.url 才能生成正确的绝对链接
url: "https://pumadong.github.io" 
baseurl: "" # 如果你的项目在子目录下，请填写子目录名


title: 讨论一下架构
description: 老骥伏枥，志在千里；烈士暮年，壮心不已 ^_^

author:
  email: puma.dong@hotmail.com

# 在 2025 年，GitHub Pages 默认提供的 Jekyll 环境中，minima 主题默认使用的版本依然是 2.5.x 系列。
# 我们使用master分支
remote_theme: jekyll/minima@master



minima:
  # 可选值: classic, dark, auto, solarized, solarized-light, solarized-dark
  skin: solarized
  # 将此项设置为 true 即可隐藏页脚的 RSS 订阅图标/文字
  hide_site_feed_link: true
  date_format: "%Y-%m-%d"


# 插件列表
plugins:
  - jekyll-paginate


# 分页具体配置
paginate: 1          # 每页显示的文章数量
paginate_path: "/page:num/"  # 分页后的 URL 路径结构（例如 /page2/）

# show_excerpts 是否在首页显示文章摘要。
show_excerpts: true