# 必须设置 site.url 才能生成正确的绝对链接
url: "https://pumadong.github.io" 
baseurl: "" # 如果你的项目在子目录下，请填写子目录名


title: 系统架构
description: 老骥伏枥，志在千里；烈士暮年，壮心不已 ^_^

author:
  email: puma.dong@hotmail.com

# 在 2025 年，GitHub Pages 默认提供的 Jekyll 环境中，minima 主题默认使用的版本依然是 2.5.x 系列。
# 我们使用master分支
remote_theme: jekyll/minima@master



minima:
  # 可选值: classic, dark, auto, solarized, solarized-light, solarized-dark
  skin: solarized
  # 将此项设置为 true 即可隐藏页脚的 RSS 订阅图标/文字
  hide_site_feed_link: true
  date_format: "%Y-%m-%d"

# 添加下面这一行，禁止 SEO 插件自动生成可能有冲突的标签
seo:
  canonical: false


# 启用插件
plugins:
  - jekyll-remote-theme
  - jekyll-paginate-v2  # 注意：这需要开启 GitHub Actions 才能运行
  - jekyll-feed


header_pages:
  - architecture.md

future: true

# Jekyll 的全局核心配置：告诉 Jekyll 核心：“我有这些目录，请把它们当成内容仓库来处理。”
# 目录必须是_开头，不是_开头的目录，Jekyll 认为里面的文件是 pages（页面），会自动抓取到 Header
collections:
  aws:
    output: true
    permalink: /aws/:title/
  docker:
    output: true
    permalink: /docker/:title/
  english:
    output: true
    permalink: /english/:title/
  optimize:
    output: true
  others:
    output: true
  spring:
    output: true
  tricks:
    output: true
         
# 分页基础配置
# jekyll-paginate-v2参数说明官网：https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 2

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/index-all/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  # category: 'posts'

  # Optional, the default tag to use, omit to disable
  # tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 0
    after: 0

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index-all'

############################################################