# 在 2025 年，GitHub Pages 默认提供的 Jekyll 环境中，minima 主题默认使用的版本依然是 2.5.x 系列。
# 我们使用master分支
remote_theme: jekyll/minima@master
title: 讨论一下架构
description: 对技术高峰，身虽不能至，而心向往之。 GitHub空间：https://github.com/pumadong。
author: Bob
email: puma.dong@hotmail.com

# 确保在 plugins 列表中包含 jekyll-feed
plugins:
  - jekyll-feed

# 必须设置 site.url 才能生成正确的绝对链接
url: "https://pumadong.github.io" 
baseurl: "" # 如果你的项目在子目录下，请填写子目录名